name: Build and Deploy

on: push

env:
  GITHUB_ORG: ${{ secrets.GH_ORG }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  deploy-repo:
    #todo change to self-hosted running
    #    if: ${{ github.ref_name == 'master' }}
    #    runs-on: [ self-hosted, linux, prod ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install libraries
        run: |
          pip install -r requirements.txt
        shell: bash
      - name: Identify user
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@bulk.com"
      - name: Apply scripts
        run: |
          chmod u+x apply.sh
          ./apply.sh
    # todo uncomment
    #      - name: Updating github PAT from secret to null
    #        run: gh secret set GH_TOKEN --body "null"
